apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  selector:
    matchLabels:
      run: sonarqube
  replicas: 1
  template:
    metadata:
      labels:
        run: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:9.9.1-community
        ports:
        - containerPort: 9000
